-- Auto-generated by gen_manifest.py — DO NOT EDIT by hand.
-- Overwritten every time the manifest is regenerated so the in-game title
-- bar can show a build identifier that changes with every dev push.
local _, ns = ...
ns.BUILD_STAMP = "20260722112318"
